name: Deploy to EC2

on:
  push:
    branches:
      - master # Verify this matches your branch name (main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 1. Trust the directory
            git config --global --add safe.directory /home/ec2-user/vaultcart

            # 2. Navigate to project
            # If the folder doesn't have .git, clone it
            if [ ! -d "/home/ec2-user/vaultcart/.git" ]; then
              cd /home/ec2-user
              git clone https://github.com/Erica881/vaultcart.git
            fi

            cd /home/ec2-user/vaultcart

            # 3. Update Code
            git fetch origin master
            git reset --hard origin/master

            # 4. Build and Restart (The .env.local created by User Data stays safe)
            npm install
            npm run build

            # Restart or Start PM2
            pm2 restart vaultcart || pm2 start npm --name "vaultcart" -- start
            pm2 save
